aliases: {}
substitute-path:
  - {from: /go/src/github.com/benjaminheng, to: /home/ben/dev}
show-location-expr: false
source-list-line-color: null
source-list-keyword-color: "\x1b[0m"
source-list-string-color: "\x1b[92m"
source-list-number-color: "\x1b[0m"
source-list-comment-color: "\x1b[95m"
source-list-arrow-color: "\x1b[93m"
debug-info-directories:
- /usr/lib/debug/.build-id
