set nocompatible
source $VIMRUNTIME/mswin.vim

filetype off
set rtp+=D:/Applications/Vim/vimfiles/bundle/Vundle.vim/
let path='D:/Applications/Vim/vimfiles/bundle'
call vundle#begin(path)
Plugin 'gmarik/Vundle.vim'
" Add plugins below
Plugin 'kien/ctrlp.vim'
Plugin 'bling/vim-airline'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'scrooloose/nerdcommenter'
Plugin 'cohama/lexima.vim'
Plugin 'pangloss/vim-javascript'
Plugin 'Valloric/YouCompleteMe'
call vundle#end()
filetype plugin indent on
filetype indent on

" General stuff
"""""""""""""""""""""""""""""""""""""""""""""
set gfn=Consolas:h10:cANSI
set encoding=utf-8
set fileencoding=utf-8
if has("win32") || has("win64")
    set directory=D:\\tmp
endif

" General options
"""""""""""""""""""""""""""""""""""""""""""""
colorscheme jellybeans
filetype on
syntax on
set guioptions-=T
set autoindent
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4
set nobackup
set laststatus=2
set winaltkeys=no
set number 
set relativenumber
set ignorecase
set smartcase
set linebreak       " word wrap
set hlsearch
set scrolloff=1
set tw=0
set fileformats=unix,dos

" Variable definitions
"""""""""""""""""""""""""""""""""""""""""""""
let &showbreak = '--- '
let mapleader = ","
let $HOME="C:\\Users\\Ben"

" Plugin 'Valloric/YouCompleteMe'
let g:ycm_path_to_python_interpreter = 'C:\\Python27\\python.exe'

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#syntastic#enabled = 0
let g:airline#extensions#tabline#show_buffers = 0
let g:airline#extensions#whitespace#checks = ['indent']
let g:airline_powerline_fonts = 1

let g:ctrlp_regexp = 1
let g:ctrlp_prompt_mappings = { 'PrtAdd(".*")': ['<space>'] }
let g:ctrlp_map = '<c-p>'
let g:ctrlp_custom_ignore = {
\   'dir': 'node_modules'
\ }

let g:syntastic_python_checkers =  ['pyflakes']

" Plugin 'pangloss/vim-javascript'
let b:javascript_fold = 0

" Auto-commands
"""""""""""""""""""""""""""""""""""""""""""""
autocmd InsertEnter * :set norelativenumber
autocmd InsertLeave * :set relativenumber

" Mappings
"""""""""""""""""""""""""""""""""""""""""""""
nmap <F8> :NERDTreeToggle<CR>
nmap <Leader>f :CtrlP<Space>
nmap <F2> :wa<Bar>exe "mksession! " . v:this_session<CR>
nmap <silent> <leader>ev :e $MYVIMRC<CR>

" fix for properly indenting lines starting with # on a new line
inoremap # X#

" map jk to <Esc>
inoremap jk <Esc>

" switch tabs
nnoremap <silent> <C-w><C-l> :tabnext<CR>
nnoremap <silent> <C-w><C-h> :tabprevious<CR>

" switch splits
nnoremap <silent> <C-h> <c-w>h
nnoremap <silent> <C-j> <c-w>j
nnoremap <silent> <C-k> <c-w>k
nnoremap <silent> <C-l> <c-w>l

" yank/paste to/from clipboard
vmap <leader>y "*y
nmap <leader>p "*p

" clear search highlighting
nmap <silent> <leader>/ :nohlsearch<CR>
