[[actions]]
name = "workspace-update-stale"
desc = "workspace update-stale"
lua = '''
jj("workspace", "update-stale")
revisions.refresh()
'''
seq = ["w", "u"]
scope = "revisions"

[[bindings]]
action = "ui.cancel"
desc = "close diff"
key = "q"
scope = "diff"

[[actions]]
name = "diff2"
desc = "jj diff2"
lua = 'exec_shell("jj diff2 --color=always -r " .. context.change_id() .. " | less -R")'
seq = [",", "d"]
scope = "revisions"
